import { NavLink, TierData } from './definitions';

export const navLinks: NavLink[] = [
  { href: '/', label: 'Home' },
  { href: '/#about', label: 'About' },
  { href: '/#benefits', label: 'Benefits' },
  { href: '/sponsor', label: 'Sponsor' },
  { href: '/contact', label: 'Contact' },
];

export const tiers: TierData[] = [
  {
    label: 'Bronze',
    price: '$1,000',
    circleColor: '#CD7F32',
    accentColor: '#CD7F32',
    accentGradient: 'linear-gradient(90deg, #CD7F32, #E8A45A)',
    badgeBg: '#FDF0E6',
    badgeColor: '#A0622A',
    btnBg: '#FDF0E6',
    btnColor: '#A0622A',
    btnBorder: '#E8C8A0',
    btnHoverBg: '#CD7F32',
    checkColor: '#CD7F32',
    features: [
      'Acknowledgement across all materials',
      '1 delegate pass',
      'Certificate of sponsorship',
      'Social media feature',
    ],
  },
  {
    label: 'Silver',
    price: '$2,500',
    circleColor: '#8E9EAB',
    accentColor: '#8E9EAB',
    accentGradient: 'linear-gradient(90deg, #8E9EAB, #BDC8D0)',
    badgeBg: '#EEF1F3',
    badgeColor: '#5A7080',
    btnBg: '#EEF1F3',
    btnColor: '#5A7080',
    btnBorder: '#C8D4DB',
    btnHoverBg: '#8E9EAB',
    checkColor: '#8E9EAB',
    features: [
      'All Bronze benefits',
      '3 delegate passes',
      'Logo on event banner',
      'Exhibition table',
      'Brand mention in opening remarks',
    ],
  },

  {
    label: 'Platinum',
    price: '$10,000',
    circleColor: '#5B6B7A',
    accentColor: '#5B6B7A',
    accentGradient: 'linear-gradient(90deg, #5B6B7A, #9BB0BE)',
    badgeBg: '#EAECF0',
    badgeColor: '#3D5060',
    btnBg: '#EAECF0',
    btnColor: '#3D5060',
    btnBorder: '#B0BCC5',
    btnHoverBg: '#5B6B7A',
    checkColor: '#5B6B7A',
    features: [
      'All Gold benefits',
      'Unlimited delegate passes',
      'Headline logo on all collateral',
      'Keynote speaking slot (30 mins)',
      'VIP networking dinner access',
      'Exclusive post-event report',
      'Full delegate database access',
    ],
  },
  {
    label: 'Gold',
    price: '$5,000',
    circleColor: '#F0C968',
    accentColor: '#2A2518',
    accentGradient: 'linear-gradient(90deg, #C9972A, #F0C968)',
    badgeBg: '#2A2518',
    badgeColor: '#F0C968',
    btnBg: '#C9972A',
    btnColor: '#1C1A17',
    btnBorder: '#C9972A',
    btnHoverBg: '#F0C968',
    checkColor: '#F0C968',
    dark: true,
    popular: true,
    features: [
      'All Silver benefits',
      '5 delegate passes',
      'Premium logo placement',
      'Dedicated exhibition booth',
      'Speaking slot (10 mins)',
      'Branded session room',
    ],
  },
];
